baseURL = "https://ipfs.io/blog"
relativeURLs = true
googleAnalytics = "UA-52930282-2"

[params]
  domain = "ipfs.io"
  name = "IPFS Blog"
  title = "IPFS Blog"
  description = "A peer-to-peer hypermedia protocol to make the web faster, safer, and more open."
  author = "Protocol Labs"
  github = "https://github.com/ipfs/blog"
  social = [ { title = "Twitter", link = "http://twitter.com/ipfsbot" },
    { title = "Facebook", link = "https://www.facebook.com/sharer/sharer.php?u=https://ipfs.io" },
    { title = "Google", link = "https://plus.google.com/108638684245894749879" },
    { title = "YouTube", link = "https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew" } ]

[outputs]
  home = ["HTML", "RSS", "JSON"]
