baseURL = "https://blog.ipfs.io"
relativeURLs = true
ignoreFiles = [ "\\.js\\.tmp*"]

DefaultContentLanguage = "en"
languageCode = "en-us"
hasCJKLanguage = true
enableMissingTranslationPlaceholders = false
summaryLength = 20
paginate = 10

[params]
  domain = "blog.ipfs.io"
  name = "IPFS Blog"
  title = "IPFS Blog"
  description = "A peer-to-peer hypermedia protocol to make the web faster, safer, and more open."
  author = "Protocol Labs"
  github = "https://github.com/ipfs/blog"
  social = [ { title = "Twitter", link = "https://twitter.com/IPFS" },
    { title = "Facebook", link = "https://www.facebook.com/sharer/sharer.php?u=https://ipfs.io" },
    { title = "YouTube", link = "https://www.youtube.com/channel/UCdjsUXJ3QawK4O5L1kqqsew" } ]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
    [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 0
    [languages.zh-cn]
    languageName = "中文（中国）"
    contentDir = "content-i18n/zh-cn"
    languageCode = "zh-cn"
    weight = 10
